### ISSUE TITLE
Stork silently fails when :tx-data-fn has wrong arity

### ISSUE THREAD

**Issue by usasigain** [magnetcoop/stork#1]
We spent some time debugging why a transaction was not persisted, turns out it was because :tx-data-fn expected no arguments. Stork in the other hand always feeds this function with one argument - Datomic connection.
If Stork fails should notify about it.

**Comment by iarenaza** [comment]
Fixed in 2489ec9. `ensure-installed` now throws ExceptionInfo if it can apply a migration. And adds details about the failure in the `ex-data` map.
